# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bills',
            options={'ordering': ('-datePosted', '-status'), 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterField(
            model_name='bills',
            name='paymentDate',
            field=models.DateField(null=True),
        ),
    ]
