# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20160605_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='paymentDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
