# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20160605_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=2),
        ),
    ]
