# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_auto_20160609_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bills',
            options={'ordering': ('-id', '-status'), 'verbose_name_plural': 'Bills'},
        ),
        migrations.AddField(
            model_name='bills',
            name='billingMonth',    
            field=models.DateField(default='2016-04-02'),
            preserve_default=False,
        ),
    ]
