# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_auto_20160609_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='billingMonth',
        ),
        migrations.AlterField(
            model_name='bills',
            name='billingMonth2',
            field=models.DateTimeField(blank=True, default='2016-04-02', null=True),
        ),
    ]
