# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0013_auto_20160609_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='billingMonth2',
        ),
    ]
