# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe

class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0016_auto_20160609_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='billingMonth2',
        ),
    	migrations.AddField(
            model_name='bills',
            name='billingMonth',
            field=models.DateTimeField(default=django.utils.datetime_safe.date(2016,2,4)),
            preserve_default=False,
        ),
    ]
