# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0017_remove_bills_billingmonth2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='billingMonth',
        ),
    ]
