# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0019_auto_20160609_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bills',
            options={'ordering': ('-paymentDate', '-status'), 'verbose_name_plural': 'Bills'},
        ),
    ]
