# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0020_auto_20160609_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='status',
            field=models.CharField(choices=[('PD', 'Paid'), ('NP', 'Unpaid')], default='NP', max_length=2),
        ),
    ]
