# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0021_auto_20160611_0605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bills',
            options={'ordering': ('-datePosted', '-status'), 'verbose_name_plural': 'Bills'},
        ),
    ]
