# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0022_auto_20160611_0611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bills',
            options={'ordering': ('-paymentDate', '-status'), 'verbose_name_plural': 'Bills'},
        ),
    ]
